comment: false
ignore:
  - test
coverage:
  status:
    project:
      default:
        threshold: '1%'  # Allow coverage to drop by up to 1% in a PR before marking it failed
    patch:
      default:
        threshold: '10%'
